# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cDPMcdensity <- function(n, d, data, y, x, status, pdf, cdf, ngrid, npred, updateAlpha, useHyperpriors, a0, b0, m0, S0, gamma1, gamma2, nu0, Psi0, nu, nclusters, nskip, ndpost, keepevery, printevery, alpha, lambda, m_ = NULL, Psi_ = NULL, Zeta_ = NULL, Omega_ = NULL, a_gd_ = NULL, b_gd_ = NULL, lw_ = NULL, kappa_ = NULL, grid_ = NULL, xpred_ = NULL) {
    .Call(`_BNPqte_cDPMcdensity`, n, d, data, y, x, status, pdf, cdf, ngrid, npred, updateAlpha, useHyperpriors, a0, b0, m0, S0, gamma1, gamma2, nu0, Psi0, nu, nclusters, nskip, ndpost, keepevery, printevery, alpha, lambda, m_, Psi_, Zeta_, Omega_, a_gd_, b_gd_, lw_, kappa_, grid_, xpred_)
}

cDPMdensity <- function(n, d, y, status, prediction, ngrid, updateAlpha, useHyperpriors, a0, b0, m0, S0, gamma1, gamma2, nu0, Psi0, nu, nclusters, nskip, ndpost, keepevery, printevery, alpha, lambda, m_ = NULL, Psi_ = NULL, Zeta_ = NULL, Omega_ = NULL, a_gd_ = NULL, b_gd_ = NULL, lw_ = NULL, kappa_ = NULL, grid1_ = NULL, grid2_ = NULL) {
    .Call(`_BNPqte_cDPMdensity`, n, d, y, status, prediction, ngrid, updateAlpha, useHyperpriors, a0, b0, m0, S0, gamma1, gamma2, nu0, Psi0, nu, nclusters, nskip, ndpost, keepevery, printevery, alpha, lambda, m_, Psi_, Zeta_, Omega_, a_gd_, b_gd_, lw_, kappa_, grid1_, grid2_)
}

