# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cDPMcdensity <- function(n, d, data, y, x, status, diag, pdf, cdf, meanReg, ngrid, npred, hpd, bci, updateAlpha, useHyperpriors, a0, b0, m0, S0, gamma1, gamma2, nu0, Psi0, nu, nclusters, nskip, ndpost, keepevery, printevery, alpha, lambda, m_ = NULL, Psi_ = NULL, Zeta_ = NULL, Omega_ = NULL, a_gd_ = NULL, b_gd_ = NULL, lw_ = NULL, kappa_ = NULL, grid_ = NULL, xpred_ = NULL) {
    .Call(`_BNPqte_cDPMcdensity`, n, d, data, y, x, status, diag, pdf, cdf, meanReg, ngrid, npred, hpd, bci, updateAlpha, useHyperpriors, a0, b0, m0, S0, gamma1, gamma2, nu0, Psi0, nu, nclusters, nskip, ndpost, keepevery, printevery, alpha, lambda, m_, Psi_, Zeta_, Omega_, a_gd_, b_gd_, lw_, kappa_, grid_, xpred_)
}

cDPMdensity <- function(n, d, y, status, diag, prediction, ngrid, updateAlpha, useHyperpriors, a0, b0, m0, S0, gamma1, gamma2, nu0, Psi0, nu, nclusters, nskip, ndpost, keepevery, printevery, alpha, lambda, m_ = NULL, Psi_ = NULL, Zeta_ = NULL, Omega_ = NULL, a_gd_ = NULL, b_gd_ = NULL, lw_ = NULL, kappa_ = NULL, grid1_ = NULL, grid2_ = NULL) {
    .Call(`_BNPqte_cDPMdensity`, n, d, y, status, diag, prediction, ngrid, updateAlpha, useHyperpriors, a0, b0, m0, S0, gamma1, gamma2, nu0, Psi0, nu, nclusters, nskip, ndpost, keepevery, printevery, alpha, lambda, m_, Psi_, Zeta_, Omega_, a_gd_, b_gd_, lw_, kappa_, grid1_, grid2_)
}

cDPMmdensity <- function(n, d, data, y, x, diag, pdf, cdf, ngrid, grid, npred, xpred, updateAlpha, useHyperpriors, alpha, a0, b0, lambda, gamma1, gamma2, nu0, nu, nclusters, nskip, ndpost, keepevery, diri, probs, nprobs) {
    .Call(`_BNPqte_cDPMmdensity`, n, d, data, y, x, diag, pdf, cdf, ngrid, grid, npred, xpred, updateAlpha, useHyperpriors, alpha, a0, b0, lambda, gamma1, gamma2, nu0, nu, nclusters, nskip, ndpost, keepevery, diri, probs, nprobs)
}

cpDPMcdensity <- function(ngrid, npred, grid, xpred, d, nclusters, ndpost, ZetaList, OmegaList, lwList, pdf, cdf, meanReg, hpd, bci, printevery) {
    .Call(`_BNPqte_cpDPMcdensity`, ngrid, npred, grid, xpred, d, nclusters, ndpost, ZetaList, OmegaList, lwList, pdf, cdf, meanReg, hpd, bci, printevery)
}

cpDPMdensity <- function(ngrid, grid1, grid2, d, nclusters, ndpost, ZetaList, OmegaList, lwList, printevery) {
    .Call(`_BNPqte_cpDPMdensity`, ngrid, grid1, grid2, d, nclusters, ndpost, ZetaList, OmegaList, lwList, printevery)
}

rdirichlet <- function(n, probs) {
    .Call(`_BNPqte_rdirichlet`, n, probs)
}

credible_interval <- function(n, x, alphas, type) {
    .Call(`_BNPqte_credible_interval`, n, x, alphas, type)
}

quantile_fun <- function(ngrid, nprobs, ndpost, grid, probs, cdfs) {
    .Call(`_BNPqte_quantile_fun`, ngrid, nprobs, ndpost, grid, probs, cdfs)
}

