# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cDPMdensity <- function(n, d, y, prediction, ngrid, grid1, grid2, updateAlpha, useHyperpriors, a0, b0, alpha, m0, S0, m, gamma1, gamma2, lambda, nu0, Psi0, nu, Psi, nclusters, nskip, ndpost, keepevery, Zeta_ = NULL, Omega_ = NULL, a_gd_ = NULL, b_gd_ = NULL, lw_ = NULL, kappa_ = NULL) {
    .Call(`_NonParamQTE_cDPMdensity`, n, d, y, prediction, ngrid, grid1, grid2, updateAlpha, useHyperpriors, a0, b0, alpha, m0, S0, m, gamma1, gamma2, lambda, nu0, Psi0, nu, Psi, nclusters, nskip, ndpost, keepevery, Zeta_, Omega_, a_gd_, b_gd_, lw_, kappa_)
}

rcpparma_hello_world <- function() {
    .Call(`_NonParamQTE_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_NonParamQTE_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_NonParamQTE_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_NonParamQTE_rcpparma_bothproducts`, x)
}

